/**
 * Fetches the OpenAPI spec from each TTS engine API and generates TypeScript types.
 *
 * Usage:
 *   CHATTERBOX_API_URL=https://... OMNIVOICE_API_URL=https://... npm run sync-api
 *
 * Or with .env file:
 *   npm run sync-api
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import 'dotenv/config';
import openapiTS, { astToString } from 'openapi-typescript';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TYPES_DIR = path.resolve(__dirname, '../src/types');

// engine name -> env var holding its API URL; types land in src/types/<name>-api.d.ts
const ENGINES = [
  ['chatterbox', 'CHATTERBOX_API_URL'],
  ['omnivoice', 'OMNIVOICE_API_URL'],
] as const;

async function syncEngine(name: string, envVar: string) {
  const apiUrl = process.env[envVar];

  if (!apiUrl) {
    throw new Error(`${envVar} environment variable is required`);
  }

  const openApiUrl = `${apiUrl}/openapi.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  const ast = await openapiTS(new URL(openApiUrl));
  const contents = astToString(ast);

  // Add header comment
  const header = `/**
  * This file is auto-generated by scripts/sync-api.ts
  * Do not edit manually. Run \`npm run sync-api\` to regenerate.
  *
  * Generated from: ${openApiUrl}
  * Generated at: ${new Date().toISOString()}
  */
  `;

  const outputPath = path.join(TYPES_DIR, `${name}-api.d.ts`);
  fs.writeFileSync(outputPath, header + contents);
  console.log(`Types written to: ${outputPath}`);
}

async function main() {
  fs.mkdirSync(TYPES_DIR, { recursive: true });

  for (const [name, envVar] of ENGINES) {
    await syncEngine(name, envVar);
  }
}

main().catch((err: unknown) => {
  console.error('Failed to sync API types:', err);
  process.exit(1);
});
